-- 028: Add missing + new high-value fields to company_enrichment_l2
--
-- Phase 1 (data loss fix): These fields were generated by the LLM prompts
-- but never stored because _build_l2_params() did not map them.
--
-- Phase 2 (new fields): Additional high-value fields added to prompts
-- and stored for richer sales intelligence.

BEGIN;

-- ── Phase 1: Fields generated but previously not stored ──────────

ALTER TABLE company_enrichment_l2
    ADD COLUMN IF NOT EXISTS expansion           TEXT,
    ADD COLUMN IF NOT EXISTS workflow_ai_evidence TEXT,
    ADD COLUMN IF NOT EXISTS revenue_trend        TEXT,
    ADD COLUMN IF NOT EXISTS growth_signals       TEXT,
    ADD COLUMN IF NOT EXISTS regulatory_pressure  TEXT,
    ADD COLUMN IF NOT EXISTS employee_sentiment   TEXT,
    ADD COLUMN IF NOT EXISTS pitch_framing        TEXT;

-- ── Phase 2: New high-value fields ───────────────────────────────

ALTER TABLE company_enrichment_l2
    ADD COLUMN IF NOT EXISTS ma_activity             TEXT,
    ADD COLUMN IF NOT EXISTS tech_stack_categories    TEXT,
    ADD COLUMN IF NOT EXISTS fiscal_year_end          TEXT,
    ADD COLUMN IF NOT EXISTS digital_maturity_score   TEXT,
    ADD COLUMN IF NOT EXISTS it_spend_indicators      TEXT;

COMMIT;
