-- 039: Add new person enrichment fields to contact_enrichment
-- BL-153/BL-184: 11 new columns generated by person_enricher prompts
-- that need to be stored and returned via the API.

BEGIN;

ALTER TABLE contact_enrichment
    ADD COLUMN IF NOT EXISTS education              TEXT,
    ADD COLUMN IF NOT EXISTS certifications         TEXT,
    ADD COLUMN IF NOT EXISTS expertise_areas        JSONB DEFAULT '[]',
    ADD COLUMN IF NOT EXISTS budget_signals         TEXT,
    ADD COLUMN IF NOT EXISTS buying_signals         TEXT,
    ADD COLUMN IF NOT EXISTS pain_indicators        TEXT,
    ADD COLUMN IF NOT EXISTS technology_interests   JSONB DEFAULT '[]',
    ADD COLUMN IF NOT EXISTS personalization_angle  TEXT,
    ADD COLUMN IF NOT EXISTS connection_points      JSONB DEFAULT '[]',
    ADD COLUMN IF NOT EXISTS conversation_starters  TEXT,
    ADD COLUMN IF NOT EXISTS objection_prediction   TEXT;

COMMIT;
