#!/usr/bin/env bash
# Pull secrets from the staging VPS and generate .env.dev for local development.
#
# Usage:
#   bash scripts/init-env.sh
#
# Environment:
#   LEADGEN_SSH_KEY  — path to SSH key for staging VPS (auto-detected if unset)
#
# Output:
#   .env.dev in project root (gitignored via .env.* pattern)

set -euo pipefail

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------
STAGING_HOST="3.124.110.199"
STAGING_USER="ec2-user"
STAGING_DIR="/home/ec2-user"
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"
ENV_FILE="$PROJECT_ROOT/.env.dev"

# ---------------------------------------------------------------------------
# Resolve SSH key
# ---------------------------------------------------------------------------
resolve_ssh_key() {
  # Explicit env var takes priority
  if [ -n "${LEADGEN_SSH_KEY:-}" ] && [ -f "$LEADGEN_SSH_KEY" ]; then
    echo "$LEADGEN_SSH_KEY"
    return
  fi

  # Common locations
  local candidates=(
    "/Users/michal/Downloads/LightsailDefaultKey-eu-central-1 (1).pem"
    "$HOME/.ssh/lightsail-staging.pem"
    "$HOME/.ssh/LightsailDefaultKey-eu-central-1.pem"
  )

  for key in "${candidates[@]}"; do
    if [ -f "$key" ]; then
      echo "$key"
      return
    fi
  done

  echo ""
}

SSH_KEY="$(resolve_ssh_key)"
if [ -z "$SSH_KEY" ]; then
  echo "ERROR: Cannot find SSH key for staging VPS."
  echo "  Set LEADGEN_SSH_KEY=/path/to/key.pem and re-run."
  echo "  Searched: common locations under ~/.ssh and ~/Downloads"
  exit 1
fi

echo "==> Pulling secrets from staging VPS ($STAGING_HOST)..."
echo "    SSH key: $SSH_KEY"

# ---------------------------------------------------------------------------
# Pull env vars from the staging VPS .env file
# ---------------------------------------------------------------------------
# The staging docker-compose reads variables from $STAGING_DIR/.env on the VPS.
# We extract the specific keys we need.
REMOTE_VARS=$(ssh -i "$SSH_KEY" -o StrictHostKeyChecking=accept-new \
  "${STAGING_USER}@${STAGING_HOST}" \
  "cat ${STAGING_DIR}/.env ${STAGING_DIR}/n8n-docker-caddy/.env 2>/dev/null || true")

# Helper: extract a var value from the remote .env content
get_var() {
  local name="$1"
  echo "$REMOTE_VARS" | grep -m1 "^${name}=" | sed "s/^${name}=//" | tr -d '\r' || true
}

# ---------------------------------------------------------------------------
# Extract secrets
# ---------------------------------------------------------------------------
JWT_SECRET="$(get_var LEADGEN_JWT_SECRET)"
ANTHROPIC_KEY="$(get_var ANTHROPIC_API_KEY)"
PERPLEXITY_KEY="$(get_var PERPLEXITY_API_KEY)"
GOOGLE_CID="$(get_var GOOGLE_CLIENT_ID)"
GOOGLE_CSECRET="$(get_var GOOGLE_CLIENT_SECRET)"
OAUTH_ENC_KEY="$(get_var OAUTH_ENCRYPTION_KEY)"

# Validate we got at least the critical ones
if [ -z "$JWT_SECRET" ]; then
  echo "WARNING: LEADGEN_JWT_SECRET not found on VPS .env — using placeholder."
  JWT_SECRET="local-dev-jwt-secret-change-me"
fi

# ---------------------------------------------------------------------------
# Write .env.dev
# ---------------------------------------------------------------------------
# Back up existing file if present
if [ -f "$ENV_FILE" ]; then
  cp "$ENV_FILE" "${ENV_FILE}.bak"
  echo "    Backed up existing .env.dev → .env.dev.bak"
fi

cat > "$ENV_FILE" <<EOF
# Local development environment — generated by scripts/init-env.sh
# DO NOT COMMIT (covered by .gitignore .env.*)
# Regenerate: bash scripts/init-env.sh

# Local PostgreSQL (docker-compose.dev.yml — port 5433)
DATABASE_URL=postgresql://leadgen:leadgen@localhost:5433/leadgen

# CORS for Vite dev server (overridden per-slot by dev.sh)
CORS_ORIGINS=http://localhost:5173

# n8n — keep hosted instance (no local n8n)
N8N_BASE_URL=https://n8n.visionvolve.com

# Flask debug mode
FLASK_APP=api:create_app
FLASK_DEBUG=1

# --- Secrets pulled from staging VPS ($(date +%Y-%m-%d)) ---

JWT_SECRET_KEY=${JWT_SECRET}
GOOGLE_CLIENT_ID=${GOOGLE_CID}
GOOGLE_CLIENT_SECRET=${GOOGLE_CSECRET}
GOOGLE_REDIRECT_URI=http://localhost:5001/api/oauth/google/callback
OAUTH_ENCRYPTION_KEY=${OAUTH_ENC_KEY}
PERPLEXITY_API_KEY=${PERPLEXITY_KEY}
ANTHROPIC_API_KEY=${ANTHROPIC_KEY}
EOF

echo ""
echo "==> Done. Secrets written to .env.dev"
echo ""
echo "    Variables set:"
echo "      DATABASE_URL      = postgresql://leadgen:leadgen@localhost:5433/leadgen"
echo "      JWT_SECRET_KEY    = ${JWT_SECRET:+[set]}${JWT_SECRET:-[missing]}"
echo "      ANTHROPIC_API_KEY = ${ANTHROPIC_KEY:+[set]}${ANTHROPIC_KEY:-[missing]}"
echo "      PERPLEXITY_API_KEY= ${PERPLEXITY_KEY:+[set]}${PERPLEXITY_KEY:-[missing]}"
echo "      GOOGLE_CLIENT_ID  = ${GOOGLE_CID:+[set]}${GOOGLE_CID:-[missing]}"
echo "      GOOGLE_CLIENT_SECRET = ${GOOGLE_CSECRET:+[set]}${GOOGLE_CSECRET:-[missing]}"
echo "      OAUTH_ENCRYPTION_KEY = ${OAUTH_ENC_KEY:+[set]}${OAUTH_ENC_KEY:-[missing]}"
echo ""
echo "    Start local dev with: make dev"
